services:
    db:
        image: postgres:18beta3
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgress
          - POSTGRES_DB=mlsano
        restart: unless-stopped
        ports:
          - "5432:5432"
        volumes:
          - pgdata:/var/lib/postgresql
volumes:
  pgdata: